version: '3.7'

services:
    
  api:
    build:
      context: ./news_api
    command: python /usr/src/news_api/manage.py runserver 0.0.0.0:8100
    volumes:
      - ./news_api:/usr/src/news_api
    ports:
      - 8100:8100
    depends_on:
      - news_db

  news_db:
      image: postgres
      environment:
        - POSTGRES_DB=news_app
        - POSTGRES_USER=admindb
        - POSTGRES_PASSWORD=12345678
      container_name: news_db
      volumes:
        - pgdbdata:/var/lib/postgresql/data/
volumes:
  pgdbdata:
  

